version: "3"

services:
  apiservice:
    build: 
      context: .
      dockerfile: ./apiservice/Dockerfile
    ports: 
      - 3001:3001
    environment:
      - GRPC_PORT=:3000
      - GRPC_ADDRESS=cryptoservice
      - HTTP_PORT=:3001
    depends_on:
      - cryptoservice

  cryptoservice:
    build: 
      context: .
      dockerfile: ./cryptoservice/Dockerfile
    environment:
      - GRPC_PORT=:3000
